### ISSUE TITLE
Project Not Buildable

### ISSUE THREAD

**Issue by pathartl** [Project-Lunar/Project-Lunar-Desktop-App#2]
The project in its current state is not buildable, which has made it impossible for me to test a branch I'm working on, [LunarLib](https://github.com/Project-Lunar/Project-Lunar-Desktop-App/compare/master...pathartl:refactor/lunarlib).

The basic idea is the base functionality (adding games, mods, installing the payload) should be broken out into a separate library. This library can then be used instead of hard-baking the main logic into the UI code. It creates a more open, useful, and maintainable platform in which to build on. The fork linked above is a step in the right direction to accomplish this and implements the mod functionality. However, since I can't build the UI application, I can't do any testing whatsoever. Everything is just theory at this point.

**Comment by pathartl** [comment]
Go ahead and label as #wontfix.

**Comment by swingflip** [comment]
https://github.com/Project-Lunar/Project-Lunar-Desktop-App/commit/3d5dbf58454f2bd2f2632509c0e3a88c472ca0ac FWIW
